// <auto-generated />
using System;
using HierarchicalCatalogsView.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HierarchicalCatalogsView.Migrations
{
    [DbContext(typeof(CatalogContext))]
    [Migration("20230705174545_CreateDb")]
    partial class CreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.5.23280.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HierarchicalCatalogsView.Models.Catalog", b =>
                {
                    b.Property<int>("CatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatalogId"));

                    b.Property<string>("CatalogName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("CatalogId");

                    b.HasIndex("ParentId");

                    b.ToTable("Catalogs");
                });

            modelBuilder.Entity("HierarchicalCatalogsView.Models.Catalog", b =>
                {
                    b.HasOne("HierarchicalCatalogsView.Models.Catalog", "ParentCatalog")
                        .WithMany("ChildCatalogs")
                        .HasForeignKey("ParentId");

                    b.Navigation("ParentCatalog");
                });

            modelBuilder.Entity("HierarchicalCatalogsView.Models.Catalog", b =>
                {
                    b.Navigation("ChildCatalogs");
                });
#pragma warning restore 612, 618
        }
    }
}
